### PR TITLE
improvements of find_alsa_devices.py

### PR DESCRIPTION
**Pull request by fenrog**

### CODE REVIEW

**Review by sberl — COMMENTED** [review]
What's the purpose of saving the wave files? How would one use them?

docs/find_alsa_devices.md
line 44: refers to baudrates. But I think you mean sampling rates.

What is slugify() about? Why is it needed?

**Comment by fenrog** [comment]
Saving the wave files is not relevant for the normal user. But being able to visualize the wave files is essential for me to better understand when something goes wrong. Examples:
- My Soundblatser USB dongle captured three seconds the expected frequency then two seconds 0 Hz. The visualized signal showed, that it actually recorded about 2.7 seconds the expected frequency and then the signal fell to 0 for anout the same time. At this point I did look into the generated frequency and identified that 'speaker-test' is not suitable for this test in all situations.
- Sometimes the very first second fails while the consecutive seconds are ok. It appears as if there is a strong DC offset in the beginning, which needs some time to vanish.
- My Behringer UMC202HD has some turning knobs to adjust the input and the output amplification. Visualizing the signals helps to find the right amplification.

Baudrates is wrong, should be sampling rates.

slugify() is required in conjunction with saving the wave files. The device name is turned into a file name without using invalid characters for the file name.

**Comment by fenrog** [comment]
Hi Steve,

 

I couldn't find a methgod to add an image to my comment in github.

This is an example of the first second failing while the consecutive seconds are ok.

Vizualization helps to understand what's going on.

 

Klaus

 
 

Gesendet: Dienstag, 28. Dezember 2021 um 03:46 Uhr
Von: "Steve Berl" ***@***.***>
An: "sberl/supersid" ***@***.***>
Cc: "fenrog" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [sberl/supersid] improvements of find_alsa_devices.py (PR #37)


 

@sberl commented on this pull request.

What's the purpose of saving the wave files? How would one use them?

docs/find_alsa_devices.md
line 44: refers to baudrates. But I think you mean sampling rates.

What is slugify() about? Why is it needed?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by sberl** [comment]
Maybe add a bit in the help text about saving the wave files for debugging/troubleshooting purposes? 
Otherwise ready to merge.

**Pull request merged**
